In [6]:
import pandas
import numpy as np

def filter_by_regular(filename):
    '''
    This function should read the csv file located at filename into a pandas dataframe,
    and filter the dataframe to only rows where the 'DESCn' column has the value 'REGULAR'.
    
    For example, if the pandas dataframe is as follows:
    ,C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn
    0,A002,R051,02-00-00,05-01-11,00:00:00,REGULAR,3144312,1088151
    1,A002,R051,02-00-00,05-01-11,04:00:00,DOOR,3144335,1088159
    2,A002,R051,02-00-00,05-01-11,08:00:00,REGULAR,3144353,1088177
    3,A002,R051,02-00-00,05-01-11,12:00:00,DOOR,3144424,1088231
    
    The dataframe will look like below after filtering to only rows where DESCn column
    has the value 'REGULAR':
    0,A002,R051,02-00-00,05-01-11,00:00:00,REGULAR,3144312,1088151
    2,A002,R051,02-00-00,05-01-11,08:00:00,REGULAR,3144353,1088177
    '''
    
    turnstile_data = pandas.read_csv(filename)
    turnstile_data_df = pandas.DataFrame(turnstile_data)

    turnstile_data_df.index = np.arange(0, len(turnstile_data_df))
    turnstile_data = turnstile_data_df.loc[turnstile_data['DESCn']=='REGULAR']
    
    return turnstile_data

filter_by_regular('Quiz_6_updated_file.csv')

       C/A  UNIT       SCP     DATEn     TIMEn    DESCn  ENTRIESn   EXITSn
0     A002  R051  02-00-00  05-21-11  00:00:00  REGULAR   3169391  1097585
1     A002  R051  02-00-00  05-21-11  04:00:00  REGULAR   3169415  1097588
2     A002  R051  02-00-00  05-21-11  08:00:00  REGULAR   3169431  1097607
3     A002  R051  02-00-00  05-21-11  12:00:00  REGULAR   3169506  1097686
4     A002  R051  02-00-00  05-21-11  16:00:00  REGULAR   3169693  1097734
5     A002  R051  02-00-00  05-21-11  20:00:00  REGULAR   3169998  1097769
6     A002  R051  02-00-00  05-22-11  00:00:00  REGULAR   3170119  1097792
7     A002  R051  02-00-00  05-22-11  04:00:00  REGULAR   3170146  1097801
8     A002  R051  02-00-00  05-22-11  08:00:00  REGULAR   3170164  1097820
9     A002  R051  02-00-00  05-22-11  12:00:00  REGULAR   3170240  1097867
10    A002  R051  02-00-00  05-22-11  16:00:00  REGULAR   3170388  1097912
11    A002  R051  02-00-00  05-22-11  20:00:00  REGULAR   3170611  1097941
12    A002  R051  02-00-00  05-23-11  00:00:00  REGULAR   3170695  1097964
13    A002  R051  02-00-00  05-23-11  04:00:00  REGULAR   3170701  1097964
14    A002  R051  02-00-00  05-23-11  08:00:00  REGULAR   3170746  1098069
15    A002  R051  02-00-00  05-23-11  12:00:00  REGULAR   3170897  1098378
16    A002  R051  02-00-00  05-23-11  16:00:00  REGULAR   3171194  1098447
17    A002  R051  02-00-00  05-23-11  20:00:00  REGULAR   3172059  1098511
18    A002  R051  02-00-00  05-24-11  00:00:00  REGULAR   3172200  1098528
19    A002  R051  02-00-00  05-24-11  04:00:00  REGULAR   3172214  1098529
20    A002  R051  02-00-00  05-24-11  08:00:00  REGULAR   3172266  1098628
21    A002  R051  02-00-00  05-24-11  12:00:00  REGULAR   3172407  1098952
22    A002  R051  02-00-00  05-24-11  16:00:00  REGULAR   3172689  1099010
23    A002  R051  02-00-00  05-24-11  20:00:00  REGULAR   3173590  1099055
24    A002  R051  02-00-00  05-25-11  00:00:00  REGULAR   3173803  1099079
25    A002  R051  02-00-00  05-25-11  04:00:00  REGULAR   3173826  1099081
26    A002  R051  02-00-00  05-25-11  08:00:00  REGULAR   3173873  1099178
27    A002  R051  02-00-00  05-25-11  12:00:00  REGULAR   3174022  1099496
28    A002  R051  02-00-00  05-25-11  16:00:00  REGULAR   3174309  1099572
29    A002  R051  02-00-00  05-25-11  20:00:00  REGULAR   3175172  1099651
...    ...   ...       ...       ...       ...      ...       ...      ...
7311  A042  R086  01-00-04  05-22-11  20:00:00  REGULAR    912511  4167549
7312  A042  R086  01-00-04  05-23-11  00:00:00  REGULAR    912606  4167828
7313  A042  R086  01-00-04  05-23-11  04:00:00  REGULAR    912616  4167855
7314  A042  R086  01-00-04  05-23-11  08:00:00  REGULAR    912622  4168025
7315  A042  R086  01-00-04  05-23-11  12:00:00  REGULAR    912679  4168923
7316  A042  R086  01-00-04  05-23-11  16:00:00  REGULAR    912843  4169719
7317  A042  R086  01-00-04  05-23-11  20:00:00  REGULAR    913194  4170521
7318  A042  R086  01-00-04  05-24-11  00:00:00  REGULAR    913291  4170682
7319  A042  R086  01-00-04  05-24-11  04:00:00  REGULAR    913300  4170711
7320  A042  R086  01-00-04  05-24-11  08:00:00  REGULAR    913309  4170890
7321  A042  R086  01-00-04  05-24-11  12:00:00  REGULAR    913360  4171856
7322  A042  R086  01-00-04  05-24-11  16:00:00  REGULAR    913536  4172582
7323  A042  R086  01-00-04  05-24-11  20:00:00  REGULAR    913892  4173464
7324  A042  R086  01-00-04  05-25-11  00:00:00  REGULAR    914006  4173624
7327  A042  R086  01-00-04  05-25-11  08:00:00  REGULAR    914027  4173813
7328  A042  R086  01-00-04  05-25-11  12:00:00  REGULAR    914087  4174759
7329  A042  R086  01-00-04  05-25-11  16:00:00  REGULAR    914262  4175544
7330  A042  R086  01-00-04  05-25-11  20:00:00  REGULAR    914686  4176445
7331  A042  R086  01-00-04  05-26-11  00:00:00  REGULAR    914808  4176633
7332  A042  R086  01-00-04  05-26-11  04:00:00  REGULAR    914822  4176664
7333  A042  R086  01-00-04  05-26-11  08:00:00  REGULAR    914830  4176849
7334  A042  R086  01-00-04  05-26-11  12:00:00  REGULAR    914902  4177778
7335  A042  R086  01-00-04  05-26-11  16:00:00  REGULAR    915105  4178603
7336  A042  R086  01-00-04  05-26-11  20:00:00  REGULAR    915583  4179421
7337  A042  R086  01-00-04  05-27-11  00:00:00  REGULAR    915724  4179647
7338  A042  R086  01-00-04  05-27-11  04:00:00  REGULAR    915737  4179675
7339  A042  R086  01-00-04  05-27-11  08:00:00  REGULAR    915743  4179820
7340  A042  R086  01-00-04  05-27-11  12:00:00  REGULAR    915806  4180746
7341  A042  R086  01-00-04  05-27-11  16:00:00  REGULAR    916090  4181746
7342  A042  R086  01-00-04  05-27-11  20:00:00  REGULAR    916517  4182631

[6183 rows x 8 columns]