In [2]:
import pandas

# Function from quiz 7
def filter_by_regular(filename):
    
    turnstile_data = pandas.read_csv(filename)
    turnstile_data_df = pandas.DataFrame(turnstile_data)
    turnstile_data = turnstile_data_df.loc[turnstile_data['DESCn']=='REGULAR']
    
    return turnstile_data

In [3]:
# Function from quiz 8 

def get_hourly_entries(df):
    
    df['ENTRIESn_hourly'] = df.ENTRIESn - df.ENTRIESn.shift(1)
    df['ENTRIESn_hourly'] = df['ENTRIESn_hourly'].fillna(1)

    return df

df = filter_by_regular('Quiz_6_updated_file.csv')
get_hourly_entries(df)

,C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn,ENTRIESn_hourly
0,A002,R051,02-00-00,05-21-11,00:00:00,REGULAR,3169391,1097585,1.0
1,A002,R051,02-00-00,05-21-11,04:00:00,REGULAR,3169415,1097588,24.0
2,A002,R051,02-00-00,05-21-11,08:00:00,REGULAR,3169431,1097607,16.0
3,A002,R051,02-00-00,05-21-11,12:00:00,REGULAR,3169506,1097686,75.0
4,A002,R051,02-00-00,05-21-11,16:00:00,REGULAR,3169693,1097734,187.0
5,A002,R051,02-00-00,05-21-11,20:00:00,REGULAR,3169998,1097769,305.0
6,A002,R051,02-00-00,05-22-11,00:00:00,REGULAR,3170119,1097792,121.0
7,A002,R051,02-00-00,05-22-11,04:00:00,REGULAR,3170146,1097801,27.0
8,A002,R051,02-00-00,05-22-11,08:00:00,REGULAR,3170164,1097820,18.0
9,A002,R051,02-00-00,05-22-11,12:00:00,REGULAR,3170240,1097867,76.0
10,A002,R051,02-00-00,05-22-11,16:00:00,REGULAR,3170388,1097912,148.0
11,A002,R051,02-00-00,05-22-11,20:00:00,REGULAR,3170611,1097941,223.0
12,A002,R051,02-00-00,05-23-11,00:00:00,REGULAR,3170695,1097964,84.0
13,A002,R051,02-00-00,05-23-11,04:00:00,REGULAR,3170701,1097964,6.0
14,A002,R051,02-00-00,05-23-11,08:00:00,REGULAR,3170746,1098069,45.0
15,A002,R051,02-00-00,05-23-11,12:00:00,REGULAR,3170897,1098378,151.0
16,A002,R051,02-00-00,05-23-11,16:00:00,REGULAR,3171194,1098447,297.0
17,A002,R051,02-00-00,05-23-11,20:00:00,REGULAR,3172059,1098511,865.0
18,A002,R051,02-00-00,05-24-11,00:00:00,REGULAR,3172200,1098528,141.0
19,A002,R051,02-00-00,05-24-11,04:00:00,REGULAR,3172214,1098529,14.0
20,A002,R051,02-00-00,05-24-11,08:00:00,REGULAR,3172266,1098628,52.0
21,A002,R051,02-00-00,05-24-11,12:00:00,REGULAR,3172407,1098952,141.0
22,A002,R051,02-00-00,05-24-11,16:00:00,REGULAR,3172689,1099010,282.0
23,A002,R051,02-00-00,05-24-11,20:00:00,REGULAR,3173590,1099055,901.0
24,A002,R051,02-00-00,05-25-11,00:00:00,REGULAR,3173803,1099079,213.0
25,A002,R051,02-00-00,05-25-11,04:00:00,REGULAR,3173826,1099081,23.0
26,A002,R051,02-00-00,05-25-11,08:00:00,REGULAR,3173873,1099178,47.0
27,A002,R051,02-00-00,05-25-11,12:00:00,REGULAR,3174022,1099496,149.0
28,A002,R051,02-00-00,05-25-11,16:00:00,REGULAR,3174309,1099572,287.0
29,A002,R051,02-00-00,05-25-11,20:00:00,REGULAR,3175172,1099651,863.0
...,...,...,...,...,...,...,...,...,...
7311,A042,R086,01-00-04,05-22-11,20:00:00,REGULAR,912511,4167549,362.0
7312,A042,R086,01-00-04,05-23-11,00:00:00,REGULAR,912606,4167828,95.0
7313,A042,R086,01-00-04,05-23-11,04:00:00,REGULAR,912616,4167855,10.0
7314,A042,R086,01-00-04,05-23-11,08:00:00,REGULAR,912622,4168025,6.0
7315,A042,R086,01-00-04,05-23-11,12:00:00,REGULAR,912679,4168923,57.0
7316,A042,R086,01-00-04,05-23-11,16:00:00,REGULAR,912843,4169719,164.0
7317,A042,R086,01-00-04,05-23-11,20:00:00,REGULAR,913194,4170521,351.0
7318,A042,R086,01-00-04,05-24-11,00:00:00,REGULAR,913291,4170682,97.0
7319,A042,R086,01-00-04,05-24-11,04:00:00,REGULAR,913300,4170711,9.0
7320,A042,R086,01-00-04,05-24-11,08:00:00,REGULAR,913309,4170890,9.0
7321,A042,R086,01-00-04,05-24-11,12:00:00,REGULAR,913360,4171856,51.0
7322,A042,R086,01-00-04,05-24-11,16:00:00,REGULAR,913536,4172582,176.0
7323,A042,R086,01-00-04,05-24-11,20:00:00,REGULAR,913892,4173464,356.0
7324,A042,R086,01-00-04,05-25-11,00:00:00,REGULAR,914006,4173624,114.0
7327,A042,R086,01-00-04,05-25-11,08:00:00,REGULAR,914027,4173813,21.0
7328,A042,R086,01-00-04,05-25-11,12:00:00,REGULAR,914087,4174759,60.0
7329,A042,R086,01-00-04,05-25-11,16:00:00,REGULAR,914262,4175544,175.0
7330,A042,R086,01-00-04,05-25-11,20:00:00,REGULAR,914686,4176445,424.0
7331,A042,R086,01-00-04,05-26-11,00:00:00,REGULAR,914808,4176633,122.0
7332,A042,R086,01-00-04,05-26-11,04:00:00,REGULAR,914822,4176664,14.0
7333,A042,R086,01-00-04,05-26-11,08:00:00,REGULAR,914830,4176849,8.0
7334,A042,R086,01-00-04,05-26-11,12:00:00,REGULAR,914902,4177778,72.0
7335,A042,R086,01-00-04,05-26-11,16:00:00,REGULAR,915105,4178603,203.0
7336,A042,R086,01-00-04,05-26-11,20:00:00,REGULAR,915583,4179421,478.0
7337,A042,R086,01-00-04,05-27-11,00:00:00,REGULAR,915724,4179647,141.0
7338,A042,R086,01-00-04,05-27-11,04:00:00,REGULAR,915737,4179675,13.0
7339,A042,R086,01-00-04,05-27-11,08:00:00,REGULAR,915743,4179820,6.0
7340,A042,R086,01-00-04,05-27-11,12:00:00,REGULAR,915806,4180746,63.0
7341,A042,R086,01-00-04,05-27-11,16:00:00,REGULAR,916090,4181746,284.0
7342,A042,R086,01-00-04,05-27-11,20:00:00,REGULAR,916517,4182631,427.0

In [4]:
# Function from quiz 9

def get_hourly_exits(df):

    df['EXITSn_hourly'] = df.EXITSn - df.EXITSn.shift(1)
    df['EXITSn_hourly'] = df['EXITSn_hourly'].fillna(0)
    return df

In [5]:
# Function from quiz 10

def time_to_hour(time):
    hours = []
    for hour in time:
        hour, minutes, seconds = map(int, hour.split(":"))
        hours.append(hour)
    
    df['Hour'] = hours
    return df

In [9]:
import datetime

def reformat_subway_dates(date):
    '''
    The dates in our subway data are formatted in the format month-day-year.
    The dates in our weather underground data are formatted year-month-day.
    
    In order to join these two data sets together, we'll want the dates formatted
    the same way.  Write a function that takes as its input a date in the MTA Subway
    data format, and returns a date in the weather underground format.
    
    Hint: 
    There are a couple of useful functions in the datetime library that will
    help on this assignment, called strptime and strftime. 
    More info can be seen here and further in the documentation section:
    http://docs.python.org/2/library/datetime.html#datetime.datetime.strptime
    '''
    dates = []
    for per_date in date:   
        date_formatted = datetime.datetime.strptime(per_date, '%m-%d-%y').strftime('%Y-%m-%d')
        dates.append(date_formatted)
    
    df['DATEn'] = dates
    return df

df = filter_by_regular('Quiz_6_updated_file.csv')
df = get_hourly_entries(df)
df = get_hourly_exits(df)
df = time_to_hour(df.TIMEn)
df = reformat_subway_dates(df.DATEn)

,C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn,ENTRIESn_hourly,EXITSn_hourly,Hour
0,A002,R051,02-00-00,2011-05-21,00:00:00,REGULAR,3169391,1097585,1.0,0.0,0
1,A002,R051,02-00-00,2011-05-21,04:00:00,REGULAR,3169415,1097588,24.0,3.0,4
2,A002,R051,02-00-00,2011-05-21,08:00:00,REGULAR,3169431,1097607,16.0,19.0,8
3,A002,R051,02-00-00,2011-05-21,12:00:00,REGULAR,3169506,1097686,75.0,79.0,12
4,A002,R051,02-00-00,2011-05-21,16:00:00,REGULAR,3169693,1097734,187.0,48.0,16
5,A002,R051,02-00-00,2011-05-21,20:00:00,REGULAR,3169998,1097769,305.0,35.0,20
6,A002,R051,02-00-00,2011-05-22,00:00:00,REGULAR,3170119,1097792,121.0,23.0,0
7,A002,R051,02-00-00,2011-05-22,04:00:00,REGULAR,3170146,1097801,27.0,9.0,4
8,A002,R051,02-00-00,2011-05-22,08:00:00,REGULAR,3170164,1097820,18.0,19.0,8
9,A002,R051,02-00-00,2011-05-22,12:00:00,REGULAR,3170240,1097867,76.0,47.0,12
10,A002,R051,02-00-00,2011-05-22,16:00:00,REGULAR,3170388,1097912,148.0,45.0,16
11,A002,R051,02-00-00,2011-05-22,20:00:00,REGULAR,3170611,1097941,223.0,29.0,20
12,A002,R051,02-00-00,2011-05-23,00:00:00,REGULAR,3170695,1097964,84.0,23.0,0
13,A002,R051,02-00-00,2011-05-23,04:00:00,REGULAR,3170701,1097964,6.0,0.0,4
14,A002,R051,02-00-00,2011-05-23,08:00:00,REGULAR,3170746,1098069,45.0,105.0,8
15,A002,R051,02-00-00,2011-05-23,12:00:00,REGULAR,3170897,1098378,151.0,309.0,12
16,A002,R051,02-00-00,2011-05-23,16:00:00,REGULAR,3171194,1098447,297.0,69.0,16
17,A002,R051,02-00-00,2011-05-23,20:00:00,REGULAR,3172059,1098511,865.0,64.0,20
18,A002,R051,02-00-00,2011-05-24,00:00:00,REGULAR,3172200,1098528,141.0,17.0,0
19,A002,R051,02-00-00,2011-05-24,04:00:00,REGULAR,3172214,1098529,14.0,1.0,4
20,A002,R051,02-00-00,2011-05-24,08:00:00,REGULAR,3172266,1098628,52.0,99.0,8
21,A002,R051,02-00-00,2011-05-24,12:00:00,REGULAR,3172407,1098952,141.0,324.0,12
22,A002,R051,02-00-00,2011-05-24,16:00:00,REGULAR,3172689,1099010,282.0,58.0,16
23,A002,R051,02-00-00,2011-05-24,20:00:00,REGULAR,3173590,1099055,901.0,45.0,20
24,A002,R051,02-00-00,2011-05-25,00:00:00,REGULAR,3173803,1099079,213.0,24.0,0
25,A002,R051,02-00-00,2011-05-25,04:00:00,REGULAR,3173826,1099081,23.0,2.0,4
26,A002,R051,02-00-00,2011-05-25,08:00:00,REGULAR,3173873,1099178,47.0,97.0,8
27,A002,R051,02-00-00,2011-05-25,12:00:00,REGULAR,3174022,1099496,149.0,318.0,12
28,A002,R051,02-00-00,2011-05-25,16:00:00,REGULAR,3174309,1099572,287.0,76.0,16
29,A002,R051,02-00-00,2011-05-25,20:00:00,REGULAR,3175172,1099651,863.0,79.0,20
...,...,...,...,...,...,...,...,...,...,...,...
7311,A042,R086,01-00-04,2011-05-22,20:00:00,REGULAR,912511,4167549,362.0,1049.0,20
7312,A042,R086,01-00-04,2011-05-23,00:00:00,REGULAR,912606,4167828,95.0,279.0,0
7313,A042,R086,01-00-04,2011-05-23,04:00:00,REGULAR,912616,4167855,10.0,27.0,4
7314,A042,R086,01-00-04,2011-05-23,08:00:00,REGULAR,912622,4168025,6.0,170.0,8
7315,A042,R086,01-00-04,2011-05-23,12:00:00,REGULAR,912679,4168923,57.0,898.0,12
7316,A042,R086,01-00-04,2011-05-23,16:00:00,REGULAR,912843,4169719,164.0,796.0,16
7317,A042,R086,01-00-04,2011-05-23,20:00:00,REGULAR,913194,4170521,351.0,802.0,20
7318,A042,R086,01-00-04,2011-05-24,00:00:00,REGULAR,913291,4170682,97.0,161.0,0
7319,A042,R086,01-00-04,2011-05-24,04:00:00,REGULAR,913300,4170711,9.0,29.0,4
7320,A042,R086,01-00-04,2011-05-24,08:00:00,REGULAR,913309,4170890,9.0,179.0,8
7321,A042,R086,01-00-04,2011-05-24,12:00:00,REGULAR,913360,4171856,51.0,966.0,12
7322,A042,R086,01-00-04,2011-05-24,16:00:00,REGULAR,913536,4172582,176.0,726.0,16
7323,A042,R086,01-00-04,2011-05-24,20:00:00,REGULAR,913892,4173464,356.0,882.0,20
7324,A042,R086,01-00-04,2011-05-25,00:00:00,REGULAR,914006,4173624,114.0,160.0,0
7327,A042,R086,01-00-04,2011-05-25,08:00:00,REGULAR,914027,4173813,21.0,189.0,8
7328,A042,R086,01-00-04,2011-05-25,12:00:00,REGULAR,914087,4174759,60.0,946.0,12
7329,A042,R086,01-00-04,2011-05-25,16:00:00,REGULAR,914262,4175544,175.0,785.0,16
7330,A042,R086,01-00-04,2011-05-25,20:00:00,REGULAR,914686,4176445,424.0,901.0,20
7331,A042,R086,01-00-04,2011-05-26,00:00:00,REGULAR,914808,4176633,122.0,188.0,0
7332,A042,R086,01-00-04,2011-05-26,04:00:00,REGULAR,914822,4176664,14.0,31.0,4
7333,A042,R086,01-00-04,2011-05-26,08:00:00,REGULAR,914830,4176849,8.0,185.0,8
7334,A042,R086,01-00-04,2011-05-26,12:00:00,REGULAR,914902,4177778,72.0,929.0,12
7335,A042,R086,01-00-04,2011-05-26,16:00:00,REGULAR,915105,4178603,203.0,825.0,16
7336,A042,R086,01-00-04,2011-05-26,20:00:00,REGULAR,915583,4179421,478.0,818.0,20
7337,A042,R086,01-00-04,2011-05-27,00:00:00,REGULAR,915724,4179647,141.0,226.0,0
7338,A042,R086,01-00-04,2011-05-27,04:00:00,REGULAR,915737,4179675,13.0,28.0,4
7339,A042,R086,01-00-04,2011-05-27,08:00:00,REGULAR,915743,4179820,6.0,145.0,8
7340,A042,R086,01-00-04,2011-05-27,12:00:00,REGULAR,915806,4180746,63.0,926.0,12
7341,A042,R086,01-00-04,2011-05-27,16:00:00,REGULAR,916090,4181746,284.0,1000.0,16
7342,A042,R086,01-00-04,2011-05-27,20:00:00,REGULAR,916517,4182631,427.0,885.0,20